### PR TITLE
Add key coordinate reference

### PR DESCRIPTION
**Pull request by j-martin**
Row 4 and column 5 and 6 are wrong/don't work. This is a question disguised as a PR.

Basically, I am trying to remap the thumb clusters and the led/tab/esc/any/enter/butterfly keys, but I can't figure. Basically, I'd like to expand the documentation on L29.

### CODE REVIEW

**Comment by gedankenexperimenter** [comment]
I agree that the row & column reference is needed here; I can never remember how it works for the thumb and palm keys, myself. I think what we really need is the keyboard graphic that shows row and column for the Model 01, or at least a link to it — @algernon, do you know where to find it off the top of your head?

I can tell you that the thumb keys are not in row 4, because there is no row 4. Instead, they're columns 7 & 8. The palm keys fill in the gaps in columns 6 & 9, but that gap is in a different row than it looks like, based on the way the innermost column's keys line up.

**Comment by obra** [comment]
Because this is going to vary by device (And we already have at least one
other vendor with hardware running Kaleidoscope on the way to market) you
probably want to steer people toward the Kaleidoscope-Hardware source for
their particular device. For the Model 01
https://github.com/keyboardio/Kaleidoscope-Hardware-Model01/blob/master/src/Kaleidoscope-Hardware-Model01.h#L287
may be a good reference?
ᐧ

**Comment by noseglasses** [comment]
> graphic that shows row and column for the Model 01

Additionally to a ASCII-version of the row/column layout, I would add a link to Kaia's [keyboard-layout-editor-version](http://www.keyboard-layout-editor.com/#/gists/208ec9c7f9a08382c101b558f1d983b1) of the layout to the docs. That of course with the risk that the link becomes dysfunctional.

**Comment by obra** [comment]
I split this apart into a whitespace commit and a content commit (and fixed the name of the Model 01).

Then I merged it by hand.
Thanks!

**Pull request closed without merging**
